name: tests

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stub-tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        stack: [blade, api]
        laravel: [^9, 10.x-dev]
        args: [null, --pest]


    name: Test Stubs - Laravel ${{ matrix.laravel }} - ${{ matrix.stack }} ${{ matrix.args }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Setup Laravel
        run: |
          composer create-project laravel/laravel:${{ matrix.laravel }} .
          composer require soap/bsone-ui:@dev --no-interaction --no-update
          composer config repositories.bsone-ui '{"type": "path", "url": "bsone-ui"}' --file composer.json

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: 'bsone-ui'

      - name: Install BsOneUi
        run: |
          composer update "soap/bsone-ui" --prefer-dist --no-interaction --no-progress -W
          php artisan bsone-uie:install ${{ matrix.stack }} ${{ matrix.args }}

      - name: Install NPM dependencies
        if: matrix.stack != 'api'
        run: npm i

      - name: Compile assets
        if: matrix.stack != 'api'
        run: npm run build

      - name: Execute tests
        run: ${{ matrix.args == '--pest' && 'vendor/bin/pest' || 'vendor/bin/phpunit' }}
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
